### ISSUE TITLE
使用http API的qtalk/create_muc的时候，出现群组名称丢失的情况？

### ISSUE THREAD

**Issue by jerry-chao** [startalkIM/ejabberd#1]
**描述bug**
调用创建群的API接口出现，群组nick不正常的情况

**提供的相关信息**

* 服务代码地址
https://github.com/startalkIM/ejabberd/blob/3c1b3ba37fa801b3ba55c6dd8c8b8dfad11c0953/src/http_muc_create.erl#L46
* 日志信息
```sh
19:18:42.254 [error] SQL query 'insert into muc_vcard_info(muc_name,show_name,muc_desc,muc_title,muc_pic,version) values ('mucid7@conference.qtalk', 'mucname7', '', 'this is desc', '', 1);' failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"23505">>},{message,<<"duplicate key value violates unique constraint \"muc_vcard_info_pkey\"">>},{detail,<<"Key (muc_name)=(mucid7@conference.qtalk) already exists.">>},{115,<<"public">>},{116,<<"muc_vcard_info">>},{110,<<"muc_vcard_info_pkey">>},{file,<<"nbtinsert.c">>},{line,534},{routine,<<"_bt_check_unique">>}]
```

* 截图

![image](https://user-images.githubusercontent.com/11730593/70708576-d0a1ba00-1d15-11ea-911f-038d83630163.png)

提问的注意事项可以参考：[如何有效地报告 Bug](https://www.jianshu.com/p/84e9b5166991)

**Comment by may-liu** [comment]
请确保服务是正常运行的，如果服务运行不正常导致后台处理失败，就会导致这个问题。

可通过检查日志来发现该问题

**Comment by memacs** [comment]
已修复，建群的时候建群逻辑插入了默认群名，所以这里insert不成功，加上一个判断解决:

https://github.com/startalkIM/ejabberd/blob/master/src/http_muc_create.erl#L46-L50

commit是：https://github.com/startalkIM/ejabberd/commit/1dfb321748fcf2e4814f7231b07b677980e3cc80
