### ISSUE TITLE
crash when login with wrong password?

### ISSUE THREAD

**Issue by jerry-chao** [startalkIM/ejabberd#2]
**描述bug**
当客户端发送的password不正确的时候，会出现服务端打印一条crash日志？

**提供的相关信息**
* 服务代码地址
https://github.com/startalkIM/ejabberd/blob/8fd2b6226439e382361a26b8a9af61b7445ffcf8/src/qtalk_auth.erl#L47
* 日志信息
```
/startalk/ejabberd/var/log/ejabberd/ejabberd.log.14:2020-01-04 19:45:51.300 [info] <0.12554.2>@ejabberd_c2s:terminate:1924 Reason 
{function_clause,[{proplists,get_value,["p",
<<"iYcpiSG8EUAiOF6EDYA2ZDRbNmkYRTSCM6awRJeIDGrR03LRTz4JcWIp1XQwo2HdODPzay6q
g8UoU3XDJ44kwhNkq3UOv5dw+WOaYzpEIRQ0lwn2vOqmpMmh9qQad/6n0JUbmPk++TOhILWDcJ2r8H0X64t1wXToTi7N8lw3Ug=">>,undefined],[{file,"proplists.erl"},{line,226}]},
{qtalk_auth,do_check_host_user_auth,3,[{file,"src/qtalk_auth.erl"},{line,47}]},
{qtalk_auth,check_user_password,3,[{file,"src/qtalk_auth.erl"},{line,38}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,185}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,816}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]}
```

**Comment by may-liu** [comment]
只是个日志吧，log level的问题

**Comment by may-liu** [comment]
我想我可能没表达清楚，我是想说，只是开发者刻意想设置成error而已吧,
比如，偷懒少加了个类似 LOG_ERROR_WROING_PASSWORD 的log level.

**Comment by jerry-chao** [comment]
不是日志的级别的问题，上面贴出来的是terminate里面的日志，这个是直接出错的位置的逻辑
```
/startalk/ejabberd/var/log/ejabberd/ejabberd.log.14:2020-01-04 19:45:51.300 [error] <0.12554.2> gen_fsm <0.12554.2> in state wait_for_feature_request terminated with reason: no function clause matching proplists:get_value("p", <<"iYcpiSG8EUAiOF6EDYA2ZDRbNmkYRTSCM6awRJeIDGrR03LRTz4JcWIp1XQwo2HdODPzay6qg8UoU3XDJ44kwhNkq3UOv5d...">>, undefined) line 226
```

**Comment by jerry-chao** [comment]
https://github.com/imtalkdemo/ejabberd/commit/ac104907ab90353cc12bba289f0f9181a96c65be 
改成这种形式，会不会就可以兼容传错密码的情况下，不至于会出现一个error日志

**Comment by memacs** [comment]
当 exception 发生的时候，表示不可预料的事情发生了，每个函数只应该处理它能够处理的 exception，如果不能处理，就放它过去，交由上面的（人）去处理，处理不了就让它崩溃。

Let it Crash!

我们遵循尽早发现问题并修复问题，而不是去隐藏出现的问题，进程crash掉意味着你的输入并不是按照协议规定的，服务就会尽早的crash掉该进程，不为无用的数据做过多的处理，也让开发人员意识到客户端有非法输入，需要修复这个问题。而不是后端兼容这个错误输入。

erlang在处理这种情况的时候，有着天生的优势：

- 使用 actor model，每个代码运行的上下文都是一个单独的 process。process 是一个非常细粒度的运行时，可以把它想象成是组成一个系统的细胞。

- 引入 immutable data。数据无法改变，也就截断了被多个上下文共享的可能性，因此，process A 读取的数据坏了，不会波及到 process B（我们先把 ets table 和 database 放在一边不谈），错误隔离进一步得到保证。这一点很重要，像某个答案提及的多进程 + 共享内存 / memcached，如果共享的数据坏了，你 let it crash 一百万回，它还是读着坏数据，不 defensive coding 根本解决不了问题。

**Comment by memacs** [comment]
> [imtalkdemo/ejabberd@ac10490](https://github.com/imtalkdemo/ejabberd/commit/ac104907ab90353cc12bba289f0f9181a96c65be)
> 改成这种形式，会不会就可以兼容传错密码的情况下，不至于会出现一个error日志

这个不是传错密码了，而是没有按照规定的格式传密码。

密码不对是一种错误，不按照规定使用登录流程是另一种错误。

**Comment by jerry-chao** [comment]
这个情况是使用的星语客户端出现的，具体出现的原因我们还在排查，如果按照let it crash的说法，是不是 user_type里面进行crash会更加合适呢？因为是decode的地方出错了，但是crash的地方确在do_check_host_user_auth里面。修改成一下这种形式是不是更加的符合你们的设计理念
```
user_type(Password) ->
    case rfc4627:decode(Password) of
        {ok, {obj, [{"anony", {obj, List}}]}, []} ->
            Plat = proplists:get_value("plat", List),
            Token = proplists:get_value("token", List),
            UUID = proplists:get_value("uuid", List),
            {anony, [Plat, UUID, Token, Password]};
	{ok, {obj, [{"nauth", {obj, List}}]}, []} -> {nauth, List}
    end.
```

**Comment by memacs** [comment]
> 这个情况是使用的星语客户端出现的，具体出现的原因我们还在排查，如果按照let it crash的说法，是不是 user_type里面进行crash会更加合适呢？因为是decode的地方出错了，但是crash的地方确在do_check_host_user_auth里面。修改成一下这种形式是不是更加的符合你们的设计理念
> 
> ```
> user_type(Password) ->
>     case rfc4627:decode(Password) of
>         {ok, {obj, [{"anony", {obj, List}}]}, []} ->
>             Plat = proplists:get_value("plat", List),
>             Token = proplists:get_value("token", List),
>             UUID = proplists:get_value("uuid", List),
>             {anony, [Plat, UUID, Token, Password]};
> 	{ok, {obj, [{"nauth", {obj, List}}]}, []} -> {nauth, List}
>     end.
> ```

我们有三种登录方式，anony/nauth/_，因为第三种是最早实现，且没有标识，所以走默认的case，这个是设计之中的，所以不会让它在这里crash。

**Comment by jerry-chao** [comment]
但是按照这个user_type的逻辑，如果你是有三种的， annoy/nauth/_，里面的_应该就是一个字符串，但是在做do_check_host_user_auth的时候并没有处理字符串的场景，所以才出现了上面的function_clause；
如果_这种情况下对应的是一个list的话，是不是password在第三种情况下应该是个列表才对，但是password应该是协议中直接传过来，应该不会默认转换成一个列表的。如果如果是三种，下面就按照三种的case进行处理，如果验证字符串不对，就直接报密码错误。这种default的情况是不是可以类似处理，username="user1", password="123456"的场景， 下面的do_check也应该处理这种， 字符串密码的形式。

**Comment by memacs** [comment]
> 就

这个逻辑确实是对了，默认不应该返回{nauth,  Password}，应该返回{xxxx, Password}，然后do_check_host_user_auth加一个分支来处理老的。

**Comment by memacs** [comment]
> 但是按照这个user_type的逻辑，如果你是有三种的， annoy/nauth/_，里面的_应该就是一个字符串，但是在做do_check_host_user_auth的时候并没有处理字符串的场景，所以才出现了上面的function_clause；
> 如果_这种情况下对应的是一个list的话，是不是password在第三种情况下应该是个列表才对，但是password应该是协议中直接传过来，应该不会默认转换成一个列表的。如果如果是三种，下面就按照三种的case进行处理，如果验证字符串不对，就直接报密码错误。这种default的情况是不是可以类似处理，username="user1", password="123456"的场景， 下面的do_check也应该处理这种， 字符串密码的形式。

已修复：https://github.com/startalkIM/ejabberd/commit/9b51dfa5dbb1ca94401aacdd6c591cac7744d131

**Comment by jerry-chao** [comment]
thanks very much, 太感谢了
